# nome do pipeline
name: Primeiro CI

# Evento de disparo
on:
  push: # Sempre que houver um push o pipeline dispara
    branches: # Especifica qual a branch
      - main

# Etapas do pipeline
jobs:
  primeiro_job:
    # Maquina virtual que executa os pipeline
    runs-on: ubuntu-latest
    steps: # Etapas do pipeline
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Listar arquivos do repositório
        run: ls -la

      - name: Log de contexto
        run: |
          echo "Repo - [${{github.repository}}]"
          echo "Branch - [${{github.ref_name}}]"
          echo "Commit - [${{github.sha}}]"
