# nome do pipeline
name: Primeiro CI

# Evento de disparo
on:
  push: # Sempre que houver um push o pipeline dispara
    branches: # Especifica qual a branch
      - main

# Etapas do pipeline
jobs:
  hello:
    # Maquina virtual que executa os pipeline
    runs-on: ubuntu-latest
    steps: # Etapas do pipeline
      - run: "echo Repo: ${{github.repository}} | Branch: ${{github.ref_name}} | Commit: ${{github.sha}}"
      - run: "echo 'CI funcionando corretamente'"
